steps:
  # 1. Instalação do Vault CLI e carregamento de variáveis
  - name: 'ubuntu:20.04'
    args:
      - '-c'
      - |
        echo "Instalando Vault CLI e jq..."
        apt-get update && apt-get install -y curl jq unzip sed

        echo "Baixando Vault CLI..."
        curl -fsSL https://releases.hashicorp.com/vault/1.14.0/vault_1.14.0_linux_amd64.zip -o vault.zip
        unzip vault.zip && mv vault /usr/local/bin/vault

        echo "Autenticando no Vault..."
        export VAULT_ADDR="${_VAULT_ADDR}"
        vault login "${_VAULT_TOKEN}"

        echo "[OK][INFO] - Carregando variáveis de ambiente da aplicação ms-middleware-bot."

        valuesInfo=$(vault kv get -format json -field=data kv-k8s/apps/prod/ms/ms-middleware-bot/variables)

        if [ $? == 0 ]; then
          echo "[SUCCESS][INFO] - Variáveis de ambiente carregadas."
          for k in $(echo "$valuesInfo" | jq -r 'keys[]'); do
            echo "[OK][INFO] - Importando variável $k."
            var=$(echo "$valuesInfo" | jq -r --arg key "$k" '.[$key]')
            if [ $? == 0 ]; then
              echo "$k='$var'" >> .env
              echo "[SUCCESS][INFO] - Variável $k importada com sucesso."
            else
              echo "[FAIL][ERRO] - Falha ao importar variável $k."
              exit 1
            fi
          done
        else
          echo "[FAIL][ERRO] - Erro ao obter variáveis do Vault."
          exit 1
        fi

        echo "Conteúdo final do .env:"
        cat .env
    entrypoint: bash

  # 2. Build da imagem Docker
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/${PROJECT_ID}/digitalkcxm-ms-middleware-bot:latest'
      - '-f'
      - Dockerfile-prod
      - .

  # 3. Push da imagem Docker
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/${PROJECT_ID}/digitalkcxm-ms-middleware-bot:latest'

  # 4. Deploy no Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - digitalkcxm-ms-middleware-bot
      - '--image'
      - 'gcr.io/${PROJECT_ID}/digitalkcxm-ms-middleware-bot:latest'
      - '--platform'
      - managed
      - '--region'
      - us-central1
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _VAULT_TOKEN: hvs.MwJr02c7t6I68MuijyVvoLOe
  _VAULT_ADDR: 'http://35.226.147.77:8200'
  _SERVICE_NAME: '' # Substituir pelo nome do serviço ao criar o trigger
